### ISSUE TITLE
Unable to install paper elements via Bower

### ISSUE THREAD

**Issue by paranoid-android** [PolymerElements/paper-elements#56]
Hello,

I have a bower.json file that looks like this:

```
{
  "name": "MyApp",
  "version": "1.0.0",
  "dependencies": {
    "polymer": "Polymer/polymer#^1.2.3",
    "iron-elements": "polymerelements/iron-elements#~1.0.4",    
    "firebase-element": "GoogleWebComponents/firebase-element#~1.0.7",
    "moment": "~2.10.6"
  }
}
```

I can successfully load those components. I now want to include Paper in my app. Based on the information I found in the [docs](https://elements.polymer-project.org/guides/using-elements), I get an error when I run `bower install PolymerElements/paper-elements --save`. The error is:

```
...
bower ENOENT        ENOENT: no such file or directory, lstat '/Users/user/MyApp/src/res/components/iron-a11y-keys-behavior'

Stack trace:
statCb (/usr/local/lib/node_modules/bower/node_modules/fstream/lib/reader.js:145:25)
FSReqWrap.oncomplete (fs.js:82:15)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
System info:
Bower version: 1.6.8
Node version: 4.0.0
OS: Darwin 15.0.0 x64
```

At first, I thought the problem might be some caching, so I ran the following:

```
bower cache clean
rm -rf src/res/components
bower install 
```

Unfortunately, after attempting to install paper elements several times, I continue to get the same error.

**Comment by ebidel** [comment]
I did not have this problem just now. 

```
bower cache clean
bower install PolymerElements/paper-elements
```

bower 1.6.8

**Comment by paranoid-android** [comment]
@ebidel Thank you for your help. This is now working for me. I do not understand why it wasn't, but either way, I can now use the Paper Elements!

Thanks
